#!/bin/bash
set -e
sudo  \
	/usr/bin/qemu-system-x86_64  -kernel kernel \
	-cpu  max \
	-s \
	-m  1024m \
	-machine  q35 \
	-object  rng-random,filename=/dev/urandom,id=rng0 \
	-device  virtio-rng-pci,rng=rng0 \
	-device  e1000,netdev=n1 \
	-netdev  user,id=n1,hostfwd=tcp:127.0.0.1:23-:2222,net=192.168.1.0/24,host=192.168.1.1 \
	-serial  stdio \
	-append  'earlyprintk=ttyS0,115200 console=ttyS0' \
	-monitor  /dev/null 

