#!/bin/bash
set -e
rm -f /tmp/xxx.bin
utk -xzPath  /usr/bin/xz \
	/mnt/hgfs/rminnich/Downloads/OVMF.fd  \
	remove BdsDxe insert_dxe  up2bds.ffs  \
	remove Shell insert_dxe up2shellfull.ffs \
	save /tmp/xxx.fd
/usr/bin/qemu-system-x86_64 -nographic -net none -bios /tmp/xxx.fd
